"""
MascotForge export templates.
Generates React/Three.js JSX, Python spec files, and AI prompts from a MascotSpec dict.
"""
import json


def generate_jsx_export(spec: dict) -> str:
    meta = spec.get("meta", {})
    appearance = spec.get("appearance", {})
    dialogues = spec.get("dialogues", {})
    triggers = spec.get("triggers", [])
    name = meta.get("name", "Mascot")
    safe_name = "".join(c for c in name if c.isalnum())

    # Build event listener hooks for interaction triggers
    trigger_hooks = []
    for t in triggers:
        event = t.get("event", "")
        animation = t.get("animation", "gentle_bob")
        dialogue_key = t.get("dialogue", "on_idle")
        if event in ("on_scroll", "on_click", "on_hover"):
            js_event = {"on_scroll": "scroll", "on_click": "click", "on_hover": "mouseover"}.get(event, event)
            trigger_hooks.append(f"""
  React.useEffect(() => {{
    const handler = () => {{
      setCurrentAnimation("{animation}");
      setCurrentDialogue(SPEC.dialogues["{dialogue_key}"] || "");
    }};
    window.addEventListener("{js_event}", handler);
    return () => window.removeEventListener("{js_event}", handler);
  }}, []);""")

    hooks_code = "".join(trigger_hooks)

    body_shape = appearance.get("body_shape", "blob")
    has_arms = "true" if appearance.get("has_arms") else "false"
    has_legs = "true" if appearance.get("has_legs") else "false"
    antenna = appearance.get("has_ears_or_antenna", "none")
    size_scale = appearance.get("size_scale", 1.0)

    spec_json = json.dumps(spec, indent=2)

    code = f'''/**
 * Auto-generated by MascotForge 🤖
 * Mascot: {name}
 * Shape: {body_shape} | Material: {appearance.get("material", "matte")}
 *
 * Dependencies: npm install three @react-three/fiber @react-three/drei
 * 
 * Usage:
 *   import {safe_name}Mascot from "./{safe_name}Mascot";
 *   <{safe_name}Mascot style={{{{ width: 400, height: 400 }}}} />
 */

import React from "react";
import {{ Canvas, useFrame, useRef }} from "@react-three/fiber";
import {{ OrbitControls, Environment }} from "@react-three/drei";

// ── Mascot Spec (do not edit manually — re-export from MascotForge) ──
const SPEC = {spec_json};

// ── Derived material properties ──────────────────────────────────────
const MAT_PROPS = {{
  color: SPEC.appearance.primary_color,
  roughness:
    SPEC.appearance.material === "glossy" ? 0.08
    : SPEC.appearance.material === "warm_matte" ? 0.95
    : SPEC.appearance.material === "soft_toy" ? 0.75
    : SPEC.appearance.material === "metallic" ? 0.3 : 0.88,
  metalness: SPEC.appearance.material === "metallic" ? 0.75 : 0.0,
}};
const FACE_COLOR = SPEC.appearance.material === "warm_matte" ? "#5D4037" : "#111111";

// ── Animation engine ─────────────────────────────────────────────────
function AnimatedGroup({{ children, currentAnimation }}) {{
  const ref = useRef();
  useFrame((state) => {{
    if (!ref.current) return;
    const t = state.clock.elapsedTime;
    ref.current.position.y = 0;
    ref.current.rotation.y = 0;
    ref.current.rotation.z = 0;
    if (currentAnimation === "gentle_bob") ref.current.position.y = Math.sin(t * 2) * 0.08;
    else if (currentAnimation === "wave") ref.current.rotation.z = Math.sin(t * 4) * 0.25;
    else if (currentAnimation === "bounce") ref.current.position.y = Math.abs(Math.sin(t * 4)) * 0.2;
    else if (currentAnimation === "spin") ref.current.rotation.y += 0.04;
    else if (currentAnimation === "dance") {{ ref.current.position.y = Math.sin(t * 3) * 0.12; ref.current.rotation.y = Math.sin(t * 2) * 0.3; }}
    else if (currentAnimation === "happy_jump") {{ ref.current.position.y = Math.abs(Math.sin(t * 5)) * 0.25; }}
    else if (currentAnimation === "nod") ref.current.rotation.x = Math.sin(t * 3) * 0.2;
  }});
  return <group ref={{ref}} scale={{[{size_scale}, {size_scale}, {size_scale}]}}>{{children}}</group>;
}}

// ── Mascot geometry ──────────────────────────────────────────────────
function MascotBody() {{
  {"// chunky_robot body" if body_shape == "chunky_robot" else "// blob/creature/humanoid/geometric body"}
  {_build_body_jsx(body_shape, appearance)}
}}

// ── Dialogue bubble overlay ──────────────────────────────────────────
function DialogueBubble({{ text }}) {{
  if (!text) return null;
  return (
    <div style={{{{
      position: "absolute", top: 12, left: "50%", transform: "translateX(-50%)",
      background: "#fff", color: "#000", padding: "10px 16px",
      borderRadius: 18, borderBottomLeftRadius: 3, fontFamily: "sans-serif",
      fontSize: 13, fontWeight: 500, maxWidth: 220, textAlign: "center",
      boxShadow: "0 4px 24px rgba(0,0,0,0.18)", zIndex: 10, pointerEvents: "none",
      animation: "fadeIn 0.3s ease",
    }}}}>
      {{text}}
    </div>
  );
}}

// ── Main exported component ──────────────────────────────────────────
export default function {safe_name}Mascot({{ style, className }}) {{
  const [currentAnimation, setCurrentAnimation] = React.useState(
    SPEC.animations?.idle || "gentle_bob"
  );
  const [currentDialogue, setCurrentDialogue] = React.useState(
    SPEC.dialogues?.on_load || ""
  );
  {hooks_code}

  return (
    <div style={{{{ position: "relative", width: "100%", height: "100%", minHeight: 300, ...style }}}} className={{className}}>
      <DialogueBubble text={{currentDialogue}} />
      <Canvas camera={{{{ position: [0, 0, 3], fov: 50 }}}}>
        <ambientLight intensity={{0.6}} />
        <directionalLight position={{[5, 5, 5]}} intensity={{1.2}} castShadow />
        <pointLight position={{[-3, 3, -3]}} intensity={{0.4}} color={{SPEC.appearance.accent_color}} />
        <AnimatedGroup currentAnimation={{currentAnimation}}>
          <MascotBody />
        </AnimatedGroup>
        <OrbitControls enableZoom={{false}} enablePan={{false}} />
        <Environment preset="city" />
      </Canvas>
    </div>
  );
}}
'''
    return code


def _build_body_jsx(body_shape: str, appearance: dict) -> str:
    """Return the JSX body geometry block for a given body_shape."""
    has_arms = appearance.get("has_arms", True)
    has_legs = appearance.get("has_legs", False)
    antenna = appearance.get("has_ears_or_antenna", "none")

    arms_jsx = """
    {/* Arms */}
    <mesh position={[-0.65, -0.1, 0]}><cylinderGeometry args={[0.12, 0.1, 0.55, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>
    <mesh position={[0.65, -0.1, 0]}><cylinderGeometry args={[0.12, 0.1, 0.55, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>""" if has_arms else ""

    legs_jsx = """
    {/* Legs */}
    <mesh position={[-0.25, -0.8, 0]}><cylinderGeometry args={[0.13, 0.11, 0.45, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>
    <mesh position={[0.25, -0.8, 0]}><cylinderGeometry args={[0.13, 0.11, 0.45, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>""" if has_legs else ""

    antenna_jsx = """
    {/* Antenna */}
    <group position={[0, 0.75, 0]}>
      <mesh><cylinderGeometry args={[0.02, 0.02, 0.28]} /><meshStandardMaterial color={SPEC.appearance.secondary_color} /></mesh>
      <mesh position={[0, 0.17, 0]}><sphereGeometry args={[0.07]} /><meshStandardMaterial color={SPEC.appearance.accent_color} /></mesh>
    </group>""" if antenna == "antenna" else ""

    ears_jsx = """
    {/* Ears */}
    <mesh position={[-0.6, 0.35, 0]}><sphereGeometry args={[0.18, 16, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>
    <mesh position={[0.6, 0.35, 0]}><sphereGeometry args={[0.18, 16, 16]} /><meshStandardMaterial {...MAT_PROPS} /></mesh>""" if antenna == "ears" else ""

    if body_shape == "chunky_robot":
        return f"""
  return (
    <group>
      {{/* Torso */}}
      <mesh castShadow position={{[0, -0.2, 0]}}><boxGeometry args={{[0.95, 0.9, 0.7]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      {{/* Head */}}
      <mesh castShadow position={{[0, 0.55, 0]}}><boxGeometry args={{[0.85, 0.55, 0.65]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      {{/* Neck */}}
      <mesh position={{[0, 0.2, 0]}}><cylinderGeometry args={{[0.15, 0.18, 0.15, 16]}} /><meshStandardMaterial color={{SPEC.appearance.secondary_color}} roughness={{MAT_PROPS.roughness}} /></mesh>
      {{/* Faceplate */}}
      <mesh position={{[0, 0.55, 0.315]}}><boxGeometry args={{[0.65, 0.38, 0.05]}} /><meshStandardMaterial color={{SPEC.appearance.accent_color}} roughness={{MAT_PROPS.roughness}} /></mesh>
      {{/* Eyes */}}
      <group position={{[0, 0.55, 0.35]}}>
        <mesh position={{[-0.18, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
        <mesh position={{[0.18, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
      </group>{arms_jsx}{legs_jsx}{antenna_jsx}
    </group>
  );"""
    elif body_shape == "geometric":
        return f"""
  return (
    <group>
      <mesh castShadow><octahedronGeometry args={{[0.65, 0]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      <group position={{[0, 0.1, 0.62]}}>
        <mesh position={{[-0.12, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
        <mesh position={{[0.12, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
      </group>{antenna_jsx}
    </group>
  );"""
    elif body_shape == "humanoid":
        return f"""
  return (
    <group>
      {{/* Body */}}
      <mesh castShadow position={{[0, -0.1, 0]}}><capsuleGeometry args={{[0.3, 0.5, 8, 16]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      {{/* Head */}}
      <mesh castShadow position={{[0, 0.7, 0]}}><sphereGeometry args={{[0.38, 24, 24]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      {{/* Eyes */}}
      <group position={{[0, 0.75, 0.37]}}>
        <mesh position={{[-0.12, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
        <mesh position={{[0.12, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
      </group>{arms_jsx}{legs_jsx}{antenna_jsx}
    </group>
  );"""
    else:
        # blob / creature
        return f"""
  return (
    <group>
      <mesh castShadow><sphereGeometry args={{[0.6, 32, 32]}} /><meshStandardMaterial {{...MAT_PROPS}} /></mesh>
      {{/* Eyes */}}
      <group position={{[0, 0.1, 0.58]}}>
        <mesh position={{[-0.15, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
        <mesh position={{[0.15, 0, 0]}}><sphereGeometry args={{[0.07, 16, 16]}} /><meshBasicMaterial color={{FACE_COLOR}} /></mesh>
      </group>{ears_jsx}{arms_jsx}{antenna_jsx}
    </group>
  );"""


def generate_python_export(spec: dict) -> str:
    meta = spec.get("meta", {})
    appearance = spec.get("appearance", {})
    dialogues = spec.get("dialogues", {})
    triggers = spec.get("triggers", [])
    name = meta.get("name", "Mascot")
    safe_name = "".join(c for c in name if c.isalnum()).lower()

    trigger_lines = []
    for t in triggers:
        trigger_lines.append(
            f'    MascotTrigger(event={json.dumps(t.get("event",""))}, animation={json.dumps(t.get("animation","gentle_bob"))}, dialogue={json.dumps(t.get("dialogue","on_idle"))}, delay_ms={t.get("delay_ms", None)}),'
        )
    triggers_block = "\n".join(trigger_lines) if trigger_lines else "    # No triggers defined"

    dialogues_repr = json.dumps(dialogues, indent=8)

    return f'''# ─────────────────────────────────────────────────────────────────────
# Auto-generated by MascotForge 🤖
# Mascot: {name}
# Body: {appearance.get("body_shape", "blob")} | Material: {appearance.get("material", "matte")}
#
# Usage options:
#   1. Blender: run as a script in Blender's Python console (see bottom)
#   2. Ursina Engine: use with Entity + custom geometry builders
#   3. Any Python 3D pipeline: import the MASCOT spec and read the dataclass
# ─────────────────────────────────────────────────────────────────────

from dataclasses import dataclass, field
from typing import List, Optional
import json


@dataclass
class MascotMeta:
    name: str
    personality_tags: List[str]
    voice_style: str


@dataclass
class MascotAppearance:
    body_shape: str          # blob | humanoid | geometric | creature | chunky_robot
    primary_color: str       # hex color
    secondary_color: str
    accent_color: str
    face_style: str          # cute_dot_eyes | wide_eyes | minimal_line | robotic_visor
    has_arms: bool
    has_legs: bool
    has_ears_or_antenna: str # none | ears | antenna
    material: str            # matte | glossy | soft_toy | metallic | warm_matte
    size_scale: float


@dataclass
class MascotTrigger:
    event: str               # on_scroll | on_click | on_error | on_success | on_idle | on_hover | on_load
    animation: str           # gentle_bob | wave | dance | bounce | spin | happy_jump | nod | shake
    dialogue: str            # key from dialogues dict
    delay_ms: Optional[int] = None
    threshold: Optional[float] = None


@dataclass
class MascotSpec:
    meta: MascotMeta
    appearance: MascotAppearance
    dialogues: dict
    triggers: List[MascotTrigger] = field(default_factory=list)


# ── Instantiated spec ─────────────────────────────────────────────────
MASCOT = MascotSpec(
    meta=MascotMeta(
        name={json.dumps(meta.get("name", "Mascot"))},
        personality_tags={json.dumps(meta.get("personality_tags", []))},
        voice_style={json.dumps(meta.get("voice_style", "friendly"))},
    ),
    appearance=MascotAppearance(
        body_shape={json.dumps(appearance.get("body_shape", "blob"))},
        primary_color={json.dumps(appearance.get("primary_color", "#ff0000"))},
        secondary_color={json.dumps(appearance.get("secondary_color", "#ffffff"))},
        accent_color={json.dumps(appearance.get("accent_color", "#ffaaaa"))},
        face_style={json.dumps(appearance.get("face_style", "cute_dot_eyes"))},
        has_arms={str(appearance.get("has_arms", True))},
        has_legs={str(appearance.get("has_legs", False))},
        has_ears_or_antenna={json.dumps(appearance.get("has_ears_or_antenna", "none"))},
        material={json.dumps(appearance.get("material", "matte"))},
        size_scale={appearance.get("size_scale", 1.0)},
    ),
    dialogues={dialogues_repr},
    triggers=[
{triggers_block}
    ],
)


def hex_to_rgb(hex_color: str):
    """Convert hex string to (r, g, b) float tuple (0–1 range)."""
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))


def to_json() -> str:
    """Serialize MASCOT spec to JSON string."""
    import dataclasses
    def _convert(obj):
        if dataclasses.is_dataclass(obj):
            return {{k: _convert(v) for k, v in dataclasses.asdict(obj).items()}}
        elif isinstance(obj, list):
            return [_convert(i) for i in obj]
        return obj
    return json.dumps(_convert(MASCOT), indent=2)


# ── Blender Python usage ──────────────────────────────────────────────
# Paste the block below into Blender's Scripting tab to create your mascot:
#
# import bpy, math
# spec = MASCOT
# r, g, b = hex_to_rgb(spec.appearance.primary_color)
# s = spec.appearance.size_scale
#
# # Create body mesh
# if spec.appearance.body_shape in ("blob", "creature"):
#     bpy.ops.mesh.primitive_uv_sphere_add(radius=0.6 * s, location=(0, 0, 0))
# elif spec.appearance.body_shape == "geometric":
#     bpy.ops.mesh.primitive_ico_sphere_add(radius=0.6 * s, location=(0, 0, 0))
# elif spec.appearance.body_shape == "chunky_robot":
#     bpy.ops.mesh.primitive_cube_add(size=0.95 * s, location=(0, -0.2, 0))
#
# obj = bpy.context.active_object
# obj.name = spec.meta.name
#
# # Assign material
# mat = bpy.data.materials.new(name=spec.meta.name + "_mat")
# mat.use_nodes = True
# bsdf = mat.node_tree.nodes.get("Principled BSDF")
# bsdf.inputs["Base Color"].default_value = (r, g, b, 1.0)
# roughness = 0.9 if "matte" in spec.appearance.material else 0.1
# bsdf.inputs["Roughness"].default_value = roughness
# metalness = 0.75 if spec.appearance.material == "metallic" else 0.0
# bsdf.inputs["Metallic"].default_value = metalness
# obj.data.materials.append(mat)
# print(f"Created {{spec.meta.name}} mascot in Blender.")


if __name__ == "__main__":
    print(to_json())
'''
